version: "3.2"

networks:
  tereus_shared:
    external: true # define by API compose

services:
  transpiler:
    image: cosmtrek/air
    networks:
      - tereus_shared
    volumes:
      - ./:/app
    env_file: .env
    environment:
      air_wd: /app
    tty: true
